### ISSUE TITLE
[Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by LMarly** [ZoeyVid/parsedmarc-dockerized#64]
Hello,

I'm working on windows 11 with docker desktop.
I have a problem, the parsedmarc containers have the error : [Errno -2] Name does not resolve.

I think that maybe the problem come from the publicBaseUrl, I'm not sure to really understand what I need to put here.

```dockerfile
- "elasticsearch.hosts=http://elasticsearch:9200"
- "server.publicBaseUrl=http://localhost:9200"
``` 

I'm also wondering if the problem can come from my config.ini, because I don't use an imap account but I use Oauth2 with a shared mailbox.

```dockerfile
[general]
save_aggregate = True
save_forensic = True

[mailbox]
watch = True
delete = True

[imap]
host = outlook.office365.com
port = 993
ssl = True
user = xxxx@xxxx.com
password = xxx
```

Can you please help me to understand where the problem with the error come from ?
And also, do you think that using something different than imap can be a blocking issue ?

Thank you

**Comment by Zoey2936** [comment]
did you configured dns in docker desktop?

**Comment by LMarly** [comment]
Hello, I'm not sure.

What I done it's to go in C:/Program Files/Docker/Docker, then I edit deamon.json and I add 

```
{
  "dns": ["8.8.8.8", "127.0.0.1"]
}
```

**Comment by LMarly** [comment]
> did you configured dns in docker desktop?

**Comment by Zoey2936** [comment]
So it works now?

**Comment by LMarly** [comment]
Nope

**Comment by LMarly** [comment]
I was thinking, but I just restart the container and the same problem appears

**Comment by LMarly** [comment]
I have solve the errno 2 but I have a new erro.
For information this errno 2 is due to bad configuration in config.ini files

**Comment by Zoey2936** [comment]
Which containers log this error?

**Comment by LMarly** [comment]
The errors are on the containers parsedmarc
One of the new error is : 
```
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f438d2a8e00>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f438d2a8e00>: Failed to establish a new connection: [Errno 111] Connection refused)
```

**Comment by Zoey2936** [comment]
Can you send me the resolv config of the parse container?

**Comment by LMarly** [comment]
Finally, the problem is not solve, I have many error, all a related to IMAP.
I think this problem occur because I don't use IMAP account but Oauth2 account

**Comment by Zoey2936** [comment]
Not sure, could be

**Comment by LMarly** [comment]
Can you show how you configure your DNS in Docker please ?

**Comment by Zoey2936** [comment]
You can try to add
dns: 1.1.1.1
to the compose yaml of the container

**Comment by LMarly** [comment]
Perfect, that's work 
but now I have this : 
```
2024-07-01 16:51:21 socket.gaierror: [Errno -3] Try again
2024-07-01 16:51:29 /usr/local/bin/start.sh: line 8: can't open /tmp/export.ndjson: no such file
```
Do you know what is suppose to be in export.ndjson ?
Maybe the problem can come from the way I handle the volume : 
```
 parsedmarc:
    container_name: parsedmarc
    image: zoeyvid/parsedmarc-dockerized
    restart: always
    dns:
      - 1.1.1.1
    environment:
      - "TZ=Europe/Berlin"
    volumes:
      - "C:/...../Documents/parsedmarc/dmarcdockerized/opt/parsedmarc/conf:/etc/parsedmarc"
      - "C:/...../Documents/parsedmarc/dmarcdockerized/opt/parsedmarc/geoipupdate:/usr/share/GeoIP"
    depends_on:
      - elasticsearch
      - kibana
```
